[workspace]
authors = ["Andrei-Vlad Badelita"]
channels = ["conda-forge"]
name = "flu-h1-anderson-classification"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
biopython = ">=1.85,<2"
tqdm = ">=4.67.1,<5"
ipykernel = ">=7.0.1,<8"
aiohttp = ">=3.13.0,<4"
aiofiles = ">=25.1.0,<26"
